# Generated by Django 3.0.2 on 2020-02-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expired', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#1456ab#103265', max_length=16)),
                ('position', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expired', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#1456ab#103265', max_length=16)),
                ('priority', models.PositiveSmallIntegerField()),
                ('subtasks', models.ManyToManyField(blank=True, related_name='tasks', to='core.SubTask')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='core.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
