# Generated by Django 3.0.2 on 2020-02-06 17:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('date_expired', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#1456ab#103265', max_length=16)),
                ('position', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('date_expired', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#1456ab#103265', max_length=16)),
                ('priority', models.PositiveSmallIntegerField()),
                ('comments', models.ManyToManyField(blank=True, related_name='tasks', to='core.Comment')),
                ('subtasks', models.ManyToManyField(blank=True, related_name='tasks', to='core.SubTask')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='core.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[core.models.validate_username])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('tasks', models.ManyToManyField(blank=True, related_name='users', to='core.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
